name: maze_ball
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.28.1
  flame_forge2d: ^0.19.0+1
  get: # Use latest version

  hive_ce: # no version specified
  hive_ce_flutter: # no version specified


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background/